spring:
  datasource:
      url: jdbc:mysql://192.168.99.100:3306/littleservice?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 457420045
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200