spring:
  datasource:
      url: jdbc:mysql://localhost:3306/littleservice?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: root
      password: 457420045
      driver-class-name: com.mysql.jdbc.Driver
      max-active: 200
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: littleservice-data-center

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9121/eureka/
server:
  port: 9101

author:
  name: onlyloveyd
  website: http://www.onlyloveyd.cn/

